import type { DashboardSection } from './types'

export const dashboardSections: DashboardSection[] = [
  {
    id: 'insights',
    label: 'Insights',
    tiles: [
      { entityId: 'sensor.main_floor_temperature', label: 'Main floor', kind: 'sensor', icon: 'thermometer' },
      { entityId: 'sensor.open_weather_temperature', label: 'Outside', kind: 'sensor', icon: 'cloud-sun' },
      { entityId: 'sensor.cbr750_gateway_download_speed', label: 'Download', kind: 'sensor', icon: 'gauge' },
      { entityId: 'sensor.open_weather_humidity', label: 'Humidity', kind: 'sensor', icon: 'droplets' },
      { entityId: 'sensor.esphome_web_79cc76_salt_level_percent', label: 'Salt level', kind: 'sensor', icon: 'waves' },
      { entityId: 'sensor.dashboard_battery_level', label: 'Dashboard', kind: 'sensor', icon: 'battery' },
      { entityId: 'sensor.lawn_plant_sensor_magnolia_humidity', label: 'Magnolia moisture', kind: 'sensor', icon: 'sprout' },
      { entityId: 'sensor.lawn_plant_sensor_maple_humidity', label: 'Maple moisture', kind: 'sensor', icon: 'sprout' },
    ],
  },
  {
    id: 'home',
    label: 'Home',
    tiles: [
      { entityId: 'sensor.open_weather_temperature', label: 'Outside', kind: 'sensor', icon: 'cloud-sun' },
      { entityId: 'sensor.main_floor_temperature', label: 'Main floor', kind: 'sensor', icon: 'thermometer' },
      { entityId: 'sensor.doors_open_count', label: 'Doors', kind: 'sensor', icon: 'door-open' },
      { entityId: 'binary_sensor.cbr750_gateway_wan_status', label: 'Internet', kind: 'sensor', icon: 'wifi' },
      { entityId: 'sensor.dashboard_battery_level', label: 'Dashboard', kind: 'sensor', icon: 'battery' },
      { entityId: 'sensor.volvo_xc60_battery', label: 'XC60 battery', kind: 'sensor', icon: 'car' },
    ],
  },
  {
    id: 'health',
    label: 'Health',
    tiles: [],
  },
  {
    id: 'maintenance',
    label: 'Maintenance',
    tiles: [],
  },
  {
    id: 'world',
    label: 'World time',
    tiles: [],
  },
  {
    id: 'flights',
    label: 'Flights',
    tiles: [],
  },
  {
    id: 'network',
    label: 'Network',
    tiles: [],
  },
  {
    id: 'energy',
    label: 'Energy',
    tiles: [],
  },
  {
    id: 'volvo',
    label: 'Volvo',
    tiles: [],
  },
  {
    id: 'weather',
    label: 'Weather',
    tiles: [
      { entityId: 'weather.forecast_home', label: 'Forecast', kind: 'sensor', icon: 'cloud-sun' },
      { entityId: 'sensor.open_weather_temperature', label: 'Outside temp', kind: 'sensor', icon: 'thermometer' },
      { entityId: 'sensor.open_weather_humidity', label: 'Humidity', kind: 'sensor', icon: 'droplets' },
      { entityId: 'sensor.open_weather_windspeed', label: 'Wind speed', kind: 'sensor', icon: 'wind' },
    ],
  },
  {
    id: 'climate',
    label: 'Climate',
    tiles: [
      { entityId: 'climate.mainfoor_thermostat', label: 'Main thermostat', kind: 'thermostat', icon: 'thermometer' },
      { entityId: 'sensor.nursery_sensor_temperature', label: 'Nursery', kind: 'sensor', icon: 'baby' },
      { entityId: 'sensor.master_bedroom_master_bedroom_temperature_temperature', label: 'Primary bedroom', kind: 'sensor', icon: 'bed' },
      { entityId: 'sensor.attic_sensor_temperature', label: 'Attic', kind: 'sensor', icon: 'warehouse' },
      { entityId: 'sensor.office_temperature_temperature', label: 'Office', kind: 'sensor', icon: 'briefcase' },
      { entityId: 'sensor.media_sensor_temperature', label: 'Media room', kind: 'sensor', icon: 'tv' },
    ],
  },
  {
    id: 'security',
    label: 'Security',
    tiles: [
      { entityId: 'lock.living_room_front_door', label: 'Front door', kind: 'lock', icon: 'lock' },
      { entityId: 'lock.lawn_patio_door', label: 'Patio door', kind: 'lock', icon: 'lock' },
      { entityId: 'cover.ratgdov25i_8e54c8_door', label: 'Garage gate', kind: 'sensor', icon: 'warehouse' },
      { entityId: 'binary_sensor.main_door_door', label: 'Main door', kind: 'sensor', icon: 'door-open' },
      { entityId: 'binary_sensor.any_water_leak', label: 'Water leaks', kind: 'sensor', icon: 'droplets' },
      { entityId: 'binary_sensor.main_floor_motion', label: 'Main motion', kind: 'sensor', icon: 'scan' },
    ],
  },
  {
    id: 'lights',
    label: 'Lights',
    tiles: [
      { entityId: 'light.smart_wi_fi_switch', label: 'Porch', kind: 'toggle', icon: 'lightbulb' },
      { entityId: 'light.string_lights_backyard', label: 'Backyard string', kind: 'toggle', icon: 'sparkles' },
      { entityId: 'light.driveway_driveway', label: 'Driveway', kind: 'toggle', icon: 'lightbulb' },
      { entityId: 'light.chandelier', label: 'Chandelier', kind: 'toggle', icon: 'lamp' },
      { entityId: 'light.my_rest_light', label: 'Nursery', kind: 'toggle', icon: 'moon' },
      { entityId: 'light.media_room_media_room', label: 'Media room', kind: 'toggle', icon: 'tv' },
      { entityId: 'light.smart_wi_fi_switch_2', label: 'Pantry', kind: 'toggle', icon: 'lightbulb' },
      { entityId: 'light.smart_wi_fi_switch_3', label: 'Patio', kind: 'toggle', icon: 'lightbulb' },
      { entityId: 'light.smart_wi_fi_switch_4', label: 'Garage light', kind: 'toggle', icon: 'warehouse' },
      { entityId: 'light.media_room_media_hue', label: 'Media Hue', kind: 'toggle', icon: 'sparkles' },
      { entityId: 'light.my_rest_clock', label: 'Nursery clock', kind: 'toggle', icon: 'moon' },
    ],
  },
  {
    id: 'appliances',
    label: 'Appliances',
    tiles: [
      { entityId: 'sensor.washer_current_status', label: 'Washer', kind: 'sensor', icon: 'washing-machine' },
      { entityId: 'sensor.dryer_current_status', label: 'Dryer', kind: 'sensor', icon: 'rotate-cw' },
      { entityId: 'binary_sensor.refrigerator_door', label: 'Refrigerator', kind: 'sensor', icon: 'refrigerator' },
      { entityId: 'media_player.lg_webos_tv_oled65c3pua_2', label: 'Living room TV', kind: 'toggle', icon: 'tv' },
      { entityId: 'media_player.media_projector', label: 'Projector', kind: 'toggle', icon: 'projector' },
      { entityId: 'switch.my_rest_toddler_lock', label: 'Toddler lock', kind: 'toggle', icon: 'shield' },
      { entityId: 'fan.dyson_3wf_us_ugf5956a', label: 'Dyson fan', kind: 'toggle', icon: 'wind' },
      { entityId: 'switch.washer_power', label: 'Washer power', kind: 'toggle', icon: 'washing-machine' },
      { entityId: 'switch.dryer_power', label: 'Dryer power', kind: 'toggle', icon: 'rotate-cw' },
    ],
  },
  {
    id: 'roborock',
    label: 'Roborock',
    tiles: [],
  },
  {
    id: 'scenes',
    label: 'Scenes',
    tiles: [
      { entityId: 'scene.my_rest_bedtime', label: 'Bedtime', kind: 'sensor', icon: 'moon' },
      { entityId: 'scene.on_countertop', label: 'Countertop on', kind: 'sensor', icon: 'lightbulb' },
      { entityId: 'scene.off_counter_top', label: 'Countertop off', kind: 'sensor', icon: 'lamp' },
      { entityId: 'script.night_mode', label: 'Night mode', kind: 'sensor', icon: 'moon' },
      { entityId: 'script.kiosk_next_slide', label: 'Next dashboard', kind: 'sensor', icon: 'rotate-cw' },
      { entityId: 'script.kiosk_prev_slide', label: 'Previous dashboard', kind: 'sensor', icon: 'rotate-cw' },
    ],
  },
]
